AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/20150426231645_devise_create_users.rb'
    - 'config/initializers/devise.rb'
    - 'Vagrantfile'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Style/BlockComments:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
